export const BASE_PROOF_ABI = [
  "function certifyDocument(bytes32 _documentHash, string memory _title, uint8 _category, string memory _metadataIPFS, string memory _descriptionIPFS, bool _isPublic, address[] memory _coCertifiers, uint256 _expirationDate, string[] memory _tags, string memory _originalFilename, string memory _fileExtension) external payable returns (uint256)",
  "function certifyBulk(bytes32[] memory _documentHashes, string[] memory _titles, uint8[] memory _categories, string[] memory _metadataIPFSHashes, string[] memory _descriptionIPFSHashes, bool _isPublic, string[] memory _tags) external payable returns (uint256[] memory)",
  "function transferCertificate(uint256 _certificateId, address _newOwner) external payable",
  "function batchTransfer(uint256[] memory _certificateIds, address _newOwner) external payable",
  "function revokeCertificate(uint256 _certificateId, string memory _reasonIPFS) external",
  "function batchRevoke(uint256[] memory _certificateIds, string memory _reasonIPFS) external",
  "function renewCertificate(uint256 _certificateId, uint256 _newExpirationDate) external payable",
  "function addCoCertifier(uint256 _certificateId, address _coCertifier) external",
  "function acceptCoCertification(uint256 _certificateId) external",
  "function challengeCertificate(uint256 _certificateId, string memory _challengeIPFS) external payable",
  "function getCertificate(uint256 _certificateId) external view returns (tuple(uint256 id, bytes32 documentHash, address issuer, address owner, string title, string descriptionIPFS, uint8 category, uint256 certificationTimestamp, string metadataIPFS, bool isPublic, bool isRevoked, string revocationReasonIPFS, uint256 revocationTimestamp, address[] coCertifiers, address[] pendingCoCertifiers, uint256 expirationDate, uint256 renewalCount, string[] tags, string originalFilename, string fileExtension))",
  "function verifyDocument(bytes32 _documentHash) external view returns (bool exists, uint256 certificateId, address issuer, address currentOwner, string memory title, uint256 timestamp, bool isRevoked, bool isPublic)",
  "function getTransferHistory(uint256 _certificateId) external view returns (tuple(address from, address to, uint256 timestamp)[])",
  "function getCertificatesByIssuer(address _issuer, uint256 _offset, uint256 _limit) external view returns (uint256[] memory)",
  "function getCertificatesByOwner(address _owner, uint256 _offset, uint256 _limit) external view returns (uint256[] memory)",
  "function getCertificatesByCategory(uint8 _category, uint256 _offset, uint256 _limit) external view returns (uint256[] memory)",
  "function documentExists(bytes32 _documentHash) external view returns (bool)",
  "function getCertificateIdByHash(bytes32 _documentHash) external view returns (uint256)",
  "function getTotalCertificates() external view returns (uint256)",
  "function getPlatformStats() external view returns (uint256 _totalCertificates, uint256 _totalIssuers, uint256 _totalRevoked, uint256 totalPublic, uint256 totalPrivate)",
  "function getIssuerStats(address _issuer) external view returns (uint256 totalIssued, uint256 _totalRevoked, uint256 totalTransferred, uint256[] memory certificateIds)",
  "function getChallenge(uint256 _certificateId) external view returns (tuple(address challenger, string challengeIPFS, uint256 bondAmount, uint256 timestamp, bool resolved, bool challengerWon))",
  "function certificationFee() external view returns (uint256)",
  "function transferFee() external view returns (uint256)",
  "function revocationCooldown() external view returns (uint256)",
  "function disputePeriod() external view returns (uint256)",
  "function challengeBond() external view returns (uint256)",
  "event DocumentCertified(uint256 indexed certificateId, bytes32 indexed documentHash, address indexed issuer, string title, uint8 category, uint256 timestamp, bool isPublic)",
  "event BulkCertification(address indexed issuer, uint256[] certificateIds, uint256 totalCount, uint256 discount)",
  "event CertificateTransferred(uint256 indexed certificateId, address indexed previousOwner, address indexed newOwner, uint256 timestamp)",
  "event CertificateRevoked(uint256 indexed certificateId, address indexed revokedBy, string reasonIPFS, uint256 timestamp)",
  "event CertificateRenewed(uint256 indexed certificateId, address indexed renewedBy, uint256 newExpirationDate, uint256 renewalCount)",
  "event CoCertifierAdded(uint256 indexed certificateId, address indexed coCertifier, address indexed addedBy)",
  "event CoCertifierAccepted(uint256 indexed certificateId, address indexed coCertifier)"
] as const;
